/*
 * ATTENTION: The "eval" devtool has been used (maybe by default in mode: "development").
 * This devtool is neither made for production nor for readable output files.
 * It uses "eval()" calls to create a separate source file in the browser devtools.
 * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)
 * or disable the default devtool with "devtool: false".
 * If you are looking for production-ready output files, see mode: "production" (https://webpack.js.org/configuration/mode/).
 */
(self["webpackChunk_cjmia_dashboard"] = self["webpackChunk_cjmia_dashboard"] || []).push([["src_view_admin_keyword_components_aside_keywords_style_scss"],{

/***/ "../../node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./src/view/admin/keyword/components/aside_keywords/style.scss":
/*!***********************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ../../node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./src/view/admin/keyword/components/aside_keywords/style.scss ***!
  \***********************************************************************************************************************************************************************************************************************************************************************************/
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../../../../../../../node_modules/css-loader/dist/runtime/noSourceMaps.js */ \"../../node_modules/css-loader/dist/runtime/noSourceMaps.js\");\n/* harmony import */ var _node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../../../../../../../node_modules/css-loader/dist/runtime/api.js */ \"../../node_modules/css-loader/dist/runtime/api.js\");\n/* harmony import */ var _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1__);\n// Imports\n\n\nvar ___CSS_LOADER_EXPORT___ = _node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1___default()((_node_modules_css_loader_dist_runtime_noSourceMaps_js__WEBPACK_IMPORTED_MODULE_0___default()));\n// Module\n___CSS_LOADER_EXPORT___.push([module.id, \".ui_box {\\n  min-width: 450px;\\n}\\n.ui_box .header > .wrap h3 {\\n  gap: 8px;\\n  align-items: center;\\n}\\n.ui_box .header > .wrap div {\\n  display: flex;\\n  align-items: center;\\n  gap: 8px;\\n}\\n.ui_box .content .btn_box {\\n  display: flex;\\n  justify-content: flex-end;\\n  gap: 4px;\\n  padding: 15px 0;\\n  border-top: 1px dashed #ccc;\\n}\\n.ui_box .content .edit_box {\\n  padding: 0 0 5px 0;\\n}\\n.ui_box .content .edit_box li {\\n  margin-bottom: 10px;\\n}\\n.ui_box .content .edit_box li:not(.name) {\\n  display: grid;\\n  grid-template-columns: 70px auto;\\n}\\n.ui_box .content .edit_box li.name {\\n  padding: 10px 15px;\\n  border: 1px solid #e7e7e7;\\n  border-left-width: 8px;\\n  border-radius: 4px;\\n}\\n.ui_box .content .edit_box li.name > span {\\n  display: block;\\n  padding-bottom: 6px;\\n  line-height: 1;\\n}\\n.ui_box .content .edit_box li.name > span > * {\\n  display: inline-block;\\n  padding: 0 3px;\\n  line-height: 1;\\n  vertical-align: top;\\n}\\n.ui_box .content .edit_box li.name > strong {\\n  display: block;\\n  font-size: 1.6em;\\n}\", \"\"]);\n// Exports\n/* harmony default export */ __webpack_exports__[\"default\"] = (___CSS_LOADER_EXPORT___);\n\n\n//# sourceURL=webpack://@cjmia/dashboard/./src/view/admin/keyword/components/aside_keywords/style.scss?../../node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use%5B1%5D!../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use%5B2%5D!../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use%5B3%5D");

/***/ }),

/***/ "./src/view/admin/keyword/components/aside_keywords/style.scss":
/*!*********************************************************************!*\
  !*** ./src/view/admin/keyword/components/aside_keywords/style.scss ***!
  \*********************************************************************/
/***/ (function(module, __unused_webpack_exports, __webpack_require__) {

eval("// style-loader: Adds some css to the DOM by adding a <style> tag\n\n// load the styles\nvar content = __webpack_require__(/*! !!../../../../../../../../node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!../../../../../../../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!../../../../../../../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./style.scss */ \"../../node_modules/css-loader/dist/cjs.js??clonedRuleSet-24.use[1]!../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-24.use[2]!../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-24.use[3]!./src/view/admin/keyword/components/aside_keywords/style.scss\");\nif(content.__esModule) content = content.default;\nif(typeof content === 'string') content = [[module.id, content, '']];\nif(content.locals) module.exports = content.locals;\n// add the styles to the DOM\nvar add = (__webpack_require__(/*! !../../../../../../../../node_modules/vue-style-loader/lib/addStylesClient.js */ \"../../node_modules/vue-style-loader/lib/addStylesClient.js\")[\"default\"])\nvar update = add(\"6ed9ca2a\", content, false, {\"sourceMap\":false,\"shadowMode\":false});\n// Hot Module Replacement\nif(false) {}\n\n//# sourceURL=webpack://@cjmia/dashboard/./src/view/admin/keyword/components/aside_keywords/style.scss?");

/***/ })

}]);